/pcd2pgm:
  ros__parameters:
    file_directory: /home/hsh/workspase/hsh_ws/hsh_ros2_humble_main/
    file_name: test
    flag_pass_through: false
    map_resolution: 0.05
    map_topic_name: map
    thre_radius: 0.5
    thre_z_max: 0.35
    thre_z_min: -0.04
    thres_point_count: 10
    use_sim_time: false
