/pcd2pgm:
  ros__parameters:
    file_directory: /home/hero/ros2_humble_2D_backup/
    file_name: test1
    flag_pass_through: false
    map_resolution: 0.05
    map_topic_name: map
    thre_radius: 0.35
    thre_z_max: 0.35
    thre_z_min: -0.01
    thres_point_count: 10
    use_sim_time: false
