/icp_registration:
  ros__parameters:
    use_sim_time: false 
    rough_leaf_size: 0.4
    refine_leaf_size: 0.1
    pcd_path: "/home/hero/ros2_humble_2D/test1.pcd"
    map_frame_id: "map"
    odom_frame_id: "odom"
    # laser_frame_id: "base_link"
    laser_frame_id: "laser_link"
    # pointcloud_topic: "/livox/lidar"
    scan_topic: "/scan"
    # pointcloud_topic: "/cloud_registered"
    thresh: 0.1
    xy_offset: 0.2
    yaw_offset: 30.0
    yaw_resolution: 10.0
    # initial_pose: [0.348, 0.697, -0.012, -0.003, -0.004, -3.081]
    # initial_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
